call npm install --save-dev bdd-using
call npm install --save-dev bower
call npm install --save-dev chai
call npm install --save-dev chai-as-promised
call npm install --save-dev chromedriver
call npm install --save-dev cucumber
call npm install --save-dev del
call npm install --save-dev gulp
call npm install --save-dev gulp-angular-templatecache
call npm install --save-dev gulp-connect
call npm install --save-dev gulp-ignore
call npm install --save-dev gulp-install
call npm install --save-dev gulp-jshint
call npm install --save-dev gulp-jshint-checkstyle-reporter
call npm install --save-dev gulp-karma
call npm install --save-dev gulp-minify-css
call npm install --save-dev gulp-minify-html
call npm install --save-dev gulp-ng-config
call npm install --save-dev gulp-ngdocs
call npm install --save-dev gulp-protractor
call npm install --save-dev gulp-rev
call npm install --save-dev gulp-uglify
call npm install --save-dev gulp-usemin
call npm install --save-dev gulp-util
call npm install --save-dev gulp-war
call npm install --save-dev gulp-zip
call npm install --save-dev jasmine-core
call npm install --save-dev karma
call npm install --save-dev karma-bdd-using
call npm install --save-dev karma-chrome-launcher
call npm install --save-dev karma-coverage
call npm install --save-dev karma-jasmine
call npm install --save-dev karma-jasmine-matchers
call npm install --save-dev karma-junit-reporter
call npm install --save-dev karma-ng-html2js-preprocessor
call npm install --save-dev karma-phantomjs-launcher
call npm install --save-dev karma-story-reporter
call npm install --save-dev mkdirp
call npm install --save-dev opn
call npm install --save-dev phantomjs
call npm install --save-dev plato
call npm install --save-dev protractor
call npm install --save-dev protractor-cucumber
call npm install --save-dev selenium-server-standalone-jar
call npm install --save-dev selenium-webdriver
call npm install --save-dev shelljs
call npm install --save-dev tmp